---
title: "Burden estimates"
author: "Katy Gaythorpe"
date: "`r format(Sys.time(), '%d %B, %Y')`"
header-includes: 
- \usepackage{placeins}
output: 
  pdf_document:
    df_print: "kable"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(
  dev = "png",
  fig.path = "images/",
  dpi = 300,
  warning = FALSE,
  message = FALSE
)
```

```{r library_load}
library(YFburden)
library(dplyr)
library(magrittr)
library(tidyr)
library(snapalette)
library(KsetupR)
library(R.utils)
library(YFestimation)
library(ggplot2)
library(snapalette)
library(rgdal)
library(fields)

sourceDirectory("Functions", modifiedOnly = FALSE)

# read shapefiles in #
shp0 = rgdal::readOGR("../../shapefiles/Africa_America_0_smooth.shp",
                      stringsAsFactors = FALSE,
                      encoding = "UTF-8",
                      use_iconv = TRUE)
shp1 = rgdal::readOGR("../../shapefiles/Africa_America_1_smooth.shp",
                      stringsAsFactors = FALSE,
                      encoding = "UTF-8",
                      use_iconv = TRUE)

year_out = 2018
```


```{r load_data}

# ---------------------------------------------------------------------------
### POPULATION DATA ###

all_res_pop_3d = get_pop_data_3d() 

pop1 = all_res_pop_3d$pop1                                      
P_tot = all_res_pop_3d$P_tot                               
p_prop = all_res_pop_3d$p_prop                                  

pop1 %<>% rename(adm0_adm1 = adm1)

pop1 %<>% arrange(year) %>% dplyr::select(-c(country_code, country))

names(pop1)[3:ncol(pop1)] = paste0("a", 0:100)

pop1 %<>% filter(year<2051)
p_prop %<>% filter(year<2051)
P_tot %<>% filter(year<2051)

# ---------------------------------------------------------------------------
# VACCINATION DATA #
vc2d = readRDS("vacc_1940_1950.RDS")
vc2d = as.data.frame(vc2d)

# expand vc2d to match pop1
vc2d %<>% mutate(year = as.numeric(as.character(year)))
vc_tmp = pop1 %>% filter(!adm0_adm1 %in% vc2d$adm0_adm1)
vc_tmp[, grep("adm0_adm1|year", names(vc_tmp), invert = TRUE)] = 0

vc2d %<>% bind_rows(vc_tmp)
vc2d %<>% unique()
vc2d %<>% filter(!is.na(adm0_adm1))

```


```{r load_foi}


foi = read.csv( "FOI_samples_step_2_noagg_grouprior2.csv", stringsAsFactors = FALSE)

ve = read.csv("vac_eff_samples.csv", stringsAsFactors = FALSE)$x

# sort pop and vc to included adm1
pop1 %<>% filter(adm0_adm1 %in% names(foi))
vc2d %<>% filter(adm0_adm1 %in% names(foi))

#arrange
pop1 %<>% arrange(adm0_adm1)
vc2d %<>% arrange(adm0_adm1)
foi = foi[unique(vc2d$adm0_adm1)]


# no vacc
#vc2d[, 4:ncol(vc2d)] = 0*vc2d[, 4:ncol(vc2d)]
```


```{r calculate burden}

# ---------------------------------------------------------------------------
fun_calcBurden = function(fois, year , adm1 = NA, vc2d, pop1, ve) { # Tini's burden function
  
  if(anyNA(adm1)){
    adm1 = names(fois)
  }
  
  foi.mat = matrix(fois, nrow=length(fois), ncol=101, byrow=FALSE)
  
  class(foi.mat) = "numeric"
  
  a.mat = matrix(0:100, nrow=length(fois), ncol=101, byrow=TRUE)
  
  burden = fois * rowSums(exp(-foi.mat*a.mat) * 
                            (1-ve*vc2d[vc2d$year==year & 
                                      vc2d$adm0_adm1 %in% adm1,-(1:3)]) *
                            pop1[pop1$year==year & 
                                   pop1$adm0_adm1 %in% adm1, -(1:2)], na.rm=TRUE)
  return(burden)
}

# ---------------------------------------------------------------------------


infections_out = sapply(1:nrow(foi), FUN = function(i) fun_calcBurden(foi[i,], 
                                                                      year_out, 
                                                                      adm1 = names(foi), 
                                                                      vc2d, 
                                                                      pop1,
                                                                      ve[i]))

infections_df = as.data.frame(infections_out)
infections_df %<>% mutate(adm0_adm1 = rownames(infections_out),
                           year = year_out)
infections_df %<>% gather(sample, infections, -c(adm0_adm1, year))

infections_df %<>% mutate(adm0 = substr(adm0_adm1, 1, 3)) %>%

                   mutate(infections = as.numeric(infections)) %>%

                   mutate(prob_severe = rbeta(nrow(infections_df),
                                              6.367309,44.60736),
                          prob_severe_death = rbeta(nrow(infections_df),
                                                    16.43466, 18.49048))

infections_df %<>% mutate(severe_infections = prob_severe*infections,
                          deaths = prob_severe_death*severe_infections)

pop_df = data.frame(adm0_adm1 = pop1$adm0_adm1,
                    year = pop1$year,
                    pop = rowSums(pop1[, -c(1:2)], na.rm = TRUE))

infections_df %<>% left_join(pop_df)

infections_df %<>% mutate(severe_inci = severe_infections/pop,
                          deaths_inci = deaths/pop)
```

```{r boxplot_simple, fig.width=10, fig.height=8, eval = FALSE}

ggplot(infections_df) + 
  geom_boxplot( aes(x = adm0, y = infections)) + 
  theme(axis.text.x = element_text(angle = 90))

```

```{r infections_map, fig.cap="Mean infections in 2018- log 10 scale.", fig.width=10, fig.height=8}
colours = snapalette("Pop", 1000, type = "continuous")

tmp  = infections_df %>% 
  group_by(adm0_adm1) %>% 
  summarise(mean_infections = mean(infections, na.rm = TRUE))

shp1$infections = NA
shp1$infections = tmp$mean_infections[match(shp1$GID_1, tmp$adm0_adm1)]

mybreaks= seq(min(log10(shp1$infections), na.rm = TRUE), 
              max(log10(shp1$infections), na.rm = TRUE)+0.01, 
              length.out=1001)

vcols = findInterval(log10(shp1$infections),mybreaks)

plot(shp0)
plot(shp1, col=colours[vcols], lty=2, add=T)
plot(shp0, add = TRUE, lwd = 2)
image.plot(legend.only=TRUE, 
           breaks=mybreaks, 
           col=colours, 
           zlim=c(0,1), 
           horizontal = TRUE,
           legend.mar = 3.5)

```

```{r deaths_map, fig.cap="Mean deaths in 2018- log 10 scale.", fig.width=10, fig.height=8}
tmp  = infections_df %>% 
  group_by(adm0_adm1) %>% 
  summarise(mean_deaths = mean(deaths, na.rm = TRUE))

shp1$deaths = NA
shp1$deaths = tmp$mean_deaths[match(shp1$GID_1, tmp$adm0_adm1)]

mybreaks= seq(min(log10(shp1$deaths), na.rm = TRUE), 
              max(log10(shp1$deaths), na.rm = TRUE)+0.01, 
              length.out=1001)

vcols = findInterval(log10(shp1$deaths),mybreaks)

plot(shp0)
plot(shp1, col=colours[vcols], lty=2, add=T)
plot(shp0, add = TRUE, lwd = 2)
image.plot(legend.only=TRUE, 
           breaks=mybreaks, 
           col=colours, 
           zlim=c(0,1), 
           horizontal = TRUE,
           legend.mar = 3.5)

```

```{r deaths_precap_map, fig.cap="Mean death per capita in 2018- log 10 scale.", fig.width=10, fig.height=8}
tmp  = infections_df %>% 
  group_by(adm0_adm1) %>% 
  summarise(mean_deaths = mean(deaths, na.rm = TRUE)/mean(pop, na.rm = TRUE))

shp1$deaths = NA
shp1$deaths = tmp$mean_deaths[match(shp1$GID_1, tmp$adm0_adm1)]

mybreaks= seq(min(log10(shp1$deaths), na.rm = TRUE), 
              max(log10(shp1$deaths), na.rm = TRUE)+0.01, 
              length.out=1001)

vcols = findInterval(log10(shp1$deaths),mybreaks)

plot(shp0)
plot(shp1, col=colours[vcols], lty=2, add=T)
plot(shp0, add = TRUE, lwd = 2)
image.plot(legend.only=TRUE, 
           breaks=mybreaks, 
           col=colours, 
           zlim=c(0,1), 
           horizontal = TRUE,
           legend.mar = 3.5)

```

```{r map_deaths_country, fig.width=10, fig.height=8, fig.cap = "Mean deaths per country in 2018- log 10 scale."}
tmp = infections_df %>% 
  group_by(adm0_adm1,adm0) %>% 
  summarise(mean_deaths = mean(deaths, na.rm = TRUE))

tmp2 =  tmp %>% 
  group_by(adm0) %>% 
  summarise(sum_deaths = sum(mean_deaths, na.rm = TRUE))

shp0$deaths = NA
shp0$deaths = tmp2$sum_deaths[match(shp0$GID_0, tmp2$adm0)]
shp0$deaths[shp0$deaths == 0] = NA


mybreaks= seq(min(log10(shp0$deaths), na.rm = TRUE), 
              max(log10(shp0$deaths), na.rm = TRUE)+0.01, 
              length.out=1001)

vcols = findInterval(log10(shp0$deaths),mybreaks)

plot(shp0)
plot(shp0, col=colours[vcols], lty=2, add=T)
plot(shp0, add = TRUE, lwd = 2)
image.plot(legend.only=TRUE, 
           breaks=mybreaks, 
           col=colours, 
           zlim=c(0,1), 
           horizontal = TRUE,
           legend.mar = 3.5)

```

```{r boxplot_severe, fig.width=10, fig.height=10, fig.cap="Severe infections per country in 2018- log 10 scale."}

df = infections_df %>% 
  group_by(adm0, sample) %>% 
  summarise(severe_infections = sum(severe_infections, na.rm = TRUE))

ggplot(df) +
  geom_boxplot( aes(x = adm0, y = severe_infections, fill = adm0))  +
  theme(axis.text.x = element_text(angle = 90), legend.position = "none") +
  scale_y_log10()

```


```{r severe_table}
reporting_propn = 24000/416 # 120000/805 # 149  #Nasidi et al. 1989,
                             

df2 = df %>% 
  group_by(adm0) %>% 
  summarise(mean_severe = round(mean(severe_infections))) %>% 
  arrange(-mean_severe) %>% 
  mutate(reported_mean_severe = mean_severe/reporting_propn) %>% 
  mutate(#mean_severe = prettyNum(mean_severe, big.mark = ","),
         reported_mean_severe = prettyNum(round(reported_mean_severe), big.mark = ","))

df2

```


```{r reported_map, fig.cap="Map of countries where we may expect to see at least 1 case reported in 2018.", eval = FALSE}

shp0$reported = df2$reported_mean_severe[match( shp0$GID_0, df2$adm0)]


plot(shp0)
plot(shp0[shp0$reported>1,], col=colours[length(colours)], lty=2, add=T)
plot(shp0, add = TRUE, lwd = 2)

```


```{r cases_continent}

tmp = data.frame(countries = unique(shp0$NAME_0), adm0 = unique(shp0$GID_0))
tmp$continent <- countrycode::countrycode(sourcevar = tmp$countries,
                            origin = "country.name",
                            destination = "continent")

tmp2 = left_join(df2, tmp)

tmp2 %>% group_by(continent) %>% summarise(cases = sum(as.numeric(mean_severe), na.rm = T)) %>% mutate(percent = round(cases/sum(cases)*100))

sum(tmp2$mean_severe)
```


```{r deaths}
df = infections_df %>% 
  group_by(adm0, sample) %>% 
  summarise(deaths = sum(deaths, na.rm = TRUE))
  
df2 = df %>% 
  group_by(adm0) %>% 
  summarise(deaths = round(mean(deaths))) %>% 
  arrange(-deaths) %>% 
  mutate(reported_deaths = deaths/reporting_propn)

df2

tmp = data.frame(countries = unique(shp0$NAME_0), adm0 = unique(shp0$GID_0))
tmp$continent <- countrycode::countrycode(sourcevar = tmp$countries,
                            origin = "country.name",
                            destination = "continent")

tmp2 = left_join(df2, tmp)

tmp2 %>% group_by(continent) %>% summarise(deaths = sum(as.numeric(deaths), na.rm = T)) %>% mutate(percent = round(deaths/sum(deaths)*100))

sum(tmp2$deaths)
```


```{r c34}

c34 = read.csv("../Data/Countries.csv", stringsAsFactors = FALSE)$c34

tmp = filter(df, adm0 %in% c34)

tmp %<>% group_by(adm0) %>% 
  summarise(deaths = round(mean(deaths))) %>% 
  arrange(-deaths) %>% 
  mutate(reported_deaths = deaths/reporting_propn)

tmp

sum(tmp$deaths)

```


# Uncertainty

```{r deaths_uncert}

df = infections_df %>% 
  group_by(adm0, sample) %>% 
  summarise(deaths = sum(deaths, na.rm = TRUE))

tmp = data.frame(countries = unique(shp0$NAME_0), adm0 = unique(shp0$GID_0))
tmp$continent <- countrycode::countrycode(sourcevar = tmp$countries,
                            origin = "country.name",
                            destination = "continent")

tmp2 = left_join(df, tmp)

tmp3 = tmp2 %>% group_by(continent, sample) %>% summarise(deaths = sum(deaths))

tmp3 %>% group_by(continent) %>% 
  summarise(deaths_low = quantile(as.numeric(deaths), probs = 0.025, na.rm = T),
            deaths_median = quantile(as.numeric(deaths), probs = 0.5, na.rm = T),
            deaths_high = quantile(as.numeric(deaths), probs = 0.975, na.rm = T)) 

```