---
title: "Compare with old estimates"
author: "Katy Gaythorpe"
date: "`r format(Sys.time(), '%d %B, %Y')`"
header-includes: 
- \usepackage{placeins}
output: 
  pdf_document:
    df_print: "kable"
---

```{r knitsetup, include=FALSE}

knitr::opts_chunk$set(
  dev = "png",
  fig.path = "images/",
  dpi = 300,
  warning = FALSE,
  message = FALSE
)
```


```{r library_load}
library(YFburden)
library(dplyr)
library(magrittr)
library(tidyr)
library(snapalette)
library(KsetupR)
library(R.utils)
library(YFestimation)
library(ggplot2)
library(snapalette)
library(rgdal)
library(fields)

sourceDirectory("Functions", modifiedOnly = FALSE)

# read shapefiles in #
shp0 = rgdal::readOGR("../../shapefiles/Africa_America_0_smooth.shp",
                      stringsAsFactors = FALSE,
                      encoding = "UTF-8",
                      use_iconv = TRUE)
shp1 = rgdal::readOGR("../../shapefiles/Africa_America_1_smooth.shp",
                      stringsAsFactors = FALSE,
                      encoding = "UTF-8",
                      use_iconv = TRUE)

```


```{r read_old_foi}

old_foi <- read.csv("../VIMC_ModelRuns/central_and_code/stochastic_parameters.csv", stringsAsFactors = FALSE)

old_foi %<>% select(-c(P_severe, P_death)) %>% gather(Country, old_FOI, -run_id)

old_foi %<>% mutate(Country = gsub("FOI_", "", Country))

```

```{r read_new_foi}

foi <- read.csv( "FOI_samples_step_2_dtp3_posprior.csv", stringsAsFactors = FALSE)

foi %<>% mutate(sample = rownames(foi))

foi %<>% gather(adm1, FOI, -sample)

foi %<>% mutate(Country = substr(adm1, 1,3))

foi2 <- foi %>% group_by(Country, sample) %>% summarise(FOI = mean(FOI))

foi2 %<>% mutate(sample = as.numeric(sample))

```

Let us do some plots.

```{r combine_old_new}

foi2 %<>% filter(Country %in% old_foi$Country)

foi_comb <- left_join(foi2 %>% rename(run_id = sample), old_foi %>% filter(run_id < 101) )

foi_comb2 <- foi_comb #keep it for later

foi_comb %<>% gather(old_new, foi, -c(Country, run_id))


```

```{r boxplot, fig.height=12, fig.width=12}

ggplot(foi_comb) + 
  geom_boxplot(aes(x = old_new, y = foi, fill = old_new)) +
  theme_bw() +
  scale_fill_manual(values = snapalette("Pop", 5, type = "discrete")[c(1,5)])+
  scale_fill_viridis_d() +
  facet_wrap(~Country)

```


```{r density, fig.height=12, fig.width=12}

ggplot(foi_comb) + 
  geom_density(aes(x = foi, y = ..density.., fill = old_new)) +
  theme_bw() +
  scale_x_log10() + 
  facet_wrap(~Country) + 
  scale_fill_manual(values = alpha(snapalette("Pop", 5, type = "discrete")[c(1,5)],0.5) )+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```


```{r correlations, fig.height=12, fig.width=12}

ggplot(foi_comb2, aes(x = old_FOI, y = FOI)) +
  geom_point() + 
  stat_density_2d(aes(fill = ..level..), geom="polygon")+
     scale_fill_gradient(low=alpha(snapalette("Pop", 5, type = "discrete")[1],0.5), 
                         high=alpha(snapalette("Pop", 5, type = "discrete")[5],0.5) ) + 
  theme_bw() +
  scale_x_log10()+
  scale_y_log10() +
  stat_smooth(method = "lm", col = snapalette("Pop", 5, type = "discrete")[5])+
  geom_abline(intercept = 0, slope = 1)

```
