---
title: "GLM MCMC diagnostics Comparison"
author: "Katy Gaythorpe"
date: "`r format(Sys.time(), '%d %B, %Y')`"
header-includes: 
- \usepackage{placeins}
output: 
  pdf_document:
    df_print: "kable"
---

```{r knitsetup, include=FALSE}

knitr::opts_chunk$set(
  dev = "png",
  fig.path = "images_bestglm3/",
  dpi = 300,
  warning = FALSE,
  message = FALSE
)
```

```{r setup}
library(mcmcplots)
library(ggmcmc)
library(gridExtra)
library(maptools)
library(readr)
library(fields)
library(rgdal)
library(R.utils)
library(magrittr)
library(pROC)
library(dplyr)
library(truncdist)

# homemade
library(snapalette)
library(YFestimation)
library(KsetupR)

R.utils::sourceDirectory("Functions")

glm_mcmc_out = NULL
for(i in 1:20){
  tmp <- YFestimation::get_chains(paste0("GLM_MCMC_chain_20200115_bestglm_3_", 
                                         i),
                                  burnin =6e4, thin = 100)
  
  
  names(tmp) <- gsub("^log.", "", names(tmp))
  
  tmp %<>% mutate(variant = i)
  
  glm_mcmc_out %<>% bind_rows(tmp)
  
}

snapal <- "Pop"
```


# Compare estimates of parameters and posterior probability

```{r posteriorProb, fig.cap = "Posterior probability from entire MCMC chain, thinned by a factor 100."}

glm_mcmc_out %<>% mutate(variant = as.factor(variant))
ggplot(glm_mcmc_out) + 
  geom_violin(aes(x = reorder(variant, -posteriorProb), 
                  y = posteriorProb, fill = variant)) +
  theme_bw()+
  theme(legend.position = "none")+
  xlab("Variant") +
  ylab("Posterior probability") +
  scale_fill_manual(values = snapalette(snapal, 20, "continuous"))

```

```{r loglike, fig.cap = "Log likelihood from entire MCMC chain, thinned by a factor 100."}
GLMprior_rename = function(param) {
  
  Prior = rep(0,4)
  
  #GLM
  jj = grep("^adm05", names(param)) 
  ign = grep("low_risk", names(param))
  if(length(ign)>0)  jj = jj[jj!=ign]
  
  sd.prior = 2
  
  Prior[1] =  - 0.5 * sum((param[jj] / sd.prior) ^ 2) 
  
  Prior[2] =  sum(dnorm(as.numeric(param[grep("^adm05|family|continent|dtp", 
                                              names(param), 
                                              invert = TRUE)]),
                        mean = 0,
                        sd = 30,
                        log = TRUE), na.rm = T)
  
  Prior[3] = sum(log(dtrunc(param[grep("family", names(param))],
                        "norm",
                       mean = 0,
                       sd = 30,
                       a = 0, b = Inf)), na.rm = T)
  
  Prior[4] = sum(log(dtrunc(param[grep("low_risk", names(param))],
                            "norm",
                            mean = 0,
                            sd = 30,
                            a = 0, b = Inf)), na.rm = T)
  
  
  out = as.numeric( Prior )
  return( sum(out) )
}



glm_mcmc_out$prior <-  
  sapply(1:nrow(glm_mcmc_out),
         FUN = function(i){
           GLMprior_rename(dplyr::select(glm_mcmc_out, 
                                         -c(posteriorProb, acceptRate, variant))[i, ])
         })

glm_mcmc_out %<>% mutate(like = posteriorProb - prior)

ggplot(glm_mcmc_out) + 
  geom_violin(aes(x = reorder(variant, -like), y = like, fill = variant)) +
  theme_bw()+
  theme(legend.position = "none")+
  xlab("Variant") +
  ylab("Log Likelihood") +
  scale_fill_manual(values = snapalette(snapal, 20, "continuous"))

```

```{r individual_parameters, fig.height=12, fig.width=16}

glm_mcmc_out %>% 
  dplyr::select(-c(posteriorProb, acceptRate)) %>% 
  gather(parameter, estimates, -c(variant)) %>%
  ggplot(aes(x = variant, y = estimates, fill = variant)) +
  geom_violin()+
  theme_bw()+
  theme(legend.position = "none", axis.text.x = element_blank())+
  facet_wrap(parameter~., scales = "free")+
  scale_fill_manual(values = snapalette(snapal, 20, "continuous"))
  
```

# Compare AUC

```{r shp_etc}

### LOADING SHAPEFILES AND COUNTRIES ###
#read shapefiles in
shp0 <- rgdal::readOGR("../../shapefiles/Africa_America_0_smooth.shp",
                          stringsAsFactors = FALSE,
                          encoding = "UTF-8",
                          use_iconv = TRUE)
shp1 <- rgdal::readOGR("../../shapefiles/Africa_America_1_smooth.shp",
                          stringsAsFactors = FALSE,
                          encoding = "UTF-8",
                          use_iconv = TRUE)


#sort age vector
maxAge <- 100
ageVec <- c(0:maxAge)

### LOAD ENVIRONMENTAL DATA ###
Env_Table_path <- "../Data/Environment/global_dat"

filename <- KsetupR::get_latest_file(path = Env_Table_path, pattern = "dat_wes")


```

```{r calc_auc}

df_AUC = NULL

for(i in 1:20){
  for(s in 1:100){
  glm_tmp <-  glm_mcmc_out %>% filter(variant == i) %>% 
    dplyr::select(-c(posteriorProb, acceptRate, variant))
  Est_beta <- glm_tmp %>% sample_n(1)
  
  dat <- read.csv(filename, stringsAsFactors = FALSE)
  
  #remove families of NHP that are not to be included
  model_form_whole = read.csv("bestglm_3.csv", stringsAsFactors = FALSE) %>% 
    dplyr::select(-Criterion)
  
  covar_family = names(model_form_whole)[ which(model_form_whole[i, ] == TRUE) ] 
  
  dat <- dat[, -which(!names(dat) %in% covar_family & grepl("family", names(dat)))] 
  
  # change to just read covariates from mcmc
  covar = covar_family
  
  dat %<>% dplyr::select(-year)
  dat %<>% filter( is.finite(MIR.max))
  dat %<>% filter(!is.na(temp_mean))
  #dat %<>% tidyr::drop_na()
  dat %<>% mutate(continent = ifelse(adm0 %in% c("CIV", "STP"),
                                     "Africa", continent))
  
  #dat %<>% filter(risk %in% c("high", "moderate"))
  
  # make extra elements and normalise
  dat = adjust_env_dat(dat)
  
  
  # -----------------------------------------------------------------------
  # FIT MODEL #
  covar = covar[grep("cases_or_outbreaks|family", covar, invert = TRUE)] #
  
  
  model_form = paste0("cases_or_outbreaks~", 
                      paste(covar, collapse = "+"),
                      "+aggregate_family","+adm05", "+surv.qual.adm0") 
  

  object_glm <- YFestimation::fit_glm(dat = dat, 
                                      depi = match("cases_or_outbreaks", 
                                                   names(dat)), 
                                      models = model_form)
  
  beta0 <- object_glm[[1]]
  x <- object_glm[[2]]
  y <- object_glm[[3]]
  
  #order Est_beta to match beta0
  Est_beta = na.omit(Est_beta[names(beta0)])
  
  
  glmpreds <- YFestimation::fun_calcPred( as.numeric(Est_beta) , x, type="response")
  
  ROC_out <- pROC::roc(response = dat$cases_or_outbreaks, predictor = glmpreds)
  
  df_AUC %<>% bind_rows(c(data.frame(variant = i,
                                  sample = s,
                                  AUC = round(auc(ROC_out), 4)),
                          Est_beta))
  

  }
}

```


```{r plot_AUC, fig.cap="AUC for 100 samples of posterior for each model variant."}
df_AUC %>% mutate(variant = as.factor(variant)) %>%
ggplot( aes(x = reorder(variant, -AUC), y = AUC, fill = variant)) +
  geom_violin() +
  theme_bw()+
  theme(legend.position = "none") +
  xlab("Variant")+
  scale_fill_manual(values = snapalette(snapal, 20, "continuous"))
  
```


# Sample using AUC


```{r sample_proportionally, fig.cap="Histogram of model variant sampled according to AUC."}

n_sample = 1000

tmp = df_AUC %>% group_by(variant) %>% summarise(median_AUC = median(AUC)) %>% ungroup()

df_AUC %<>% left_join(tmp)

df_sample = df_AUC  %>% sample_n(size = n_sample, weight = AUC)

ggplot(df_sample) + geom_bar(aes(x = variant, fill = variant)) + theme_bw()

df_glm = NULL

for(i in 1:nrow(df_sample)){

  Est_beta <- df_sample[i, ] %>% select(-c(variant, sample, AUC))
  
  dat <- read.csv(filename, stringsAsFactors = FALSE)
  
  #remove families of NHP that are not to be included
  model_form_whole = read.csv("bestglm_1.csv", stringsAsFactors = FALSE) %>% 
    dplyr::select(-Criterion)
  
  covar_family = names(model_form_whole)[ 
    which(model_form_whole[df_sample$variant[i], ] == TRUE) ] 
  
  dat <- dat[, -which(!names(dat) %in% covar_family & grepl("family", names(dat)))] 
  
  # change to just read covariates from mcmc
  covar = covar_family
  
  dat %<>% dplyr::select(-year)
  dat %<>% filter( is.finite(MIR.max))
  dat %<>% filter(!is.na(temp_mean))
  #dat %<>% tidyr::drop_na()
  dat %<>% mutate(continent = ifelse(adm0 %in% c("CIV", "STP"),
                                     "Africa", continent))
  
  #dat %<>% filter(risk %in% c("high", "moderate"))
  
  # make extra elements and normalise
  dat = adjust_env_dat(dat)
  
  
  # -----------------------------------------------------------------------
  # FIT MODEL #
  covar = covar[grep("cases_or_outbreaks|family", covar, invert = TRUE)] #
  
  
  model_form = paste0("cases_or_outbreaks~", 
                      paste(covar, collapse = "+"),
                      "+aggregate_family","+adm05", "+surv.qual.adm0") 
  

  object_glm <- YFestimation::fit_glm(dat = dat, 
                                      depi = match("cases_or_outbreaks", 
                                                   names(dat)), 
                                      models = model_form)
  
  beta0 <- object_glm[[1]]
  x <- object_glm[[2]]
  y <- object_glm[[3]]
  
  #order Est_beta to match beta0
  Est_beta = na.omit(Est_beta[names(beta0)])
  
  glmpreds <- YFestimation::fun_calcPred( as.numeric(Est_beta) , x, type="response")
  
  names(glmpreds) <- dat$adm1
  
  df_glm %<>% bind_rows(glmpreds)
  
}

write.csv(df_sample, "Sampled_glm_parameters.csv", row.names = FALSE)
write.csv(df_glm, "Sampled_glm_predictions.csv", row.names = FALSE)

```


```{r map_mean_predictions}


colours <- snapalette::snapalette(snapal, 100, type = "continuous")

median_pred <-  apply(df_glm, 2, median)

shp1$predictions <- median_pred[match( shp1$GID_1, names(df_glm))]

mybreaks <- seq(0, 1.0001, length.out=101)
mycols <-  colours
vcols <- findInterval(shp1$predictions, mybreaks)


plot(shp0)
plot(shp1, col=mycols[vcols] , lty=0, add=TRUE)
plot(shp0, add=TRUE)
fields::image.plot(legend.only=TRUE, 
                   breaks=mybreaks, 
                   col=mycols, 
                   zlim=c(0,1), 
                   horizontal = TRUE)

ROC_out <- pROC::roc(response = dat$cases_or_outbreaks, predictor = median_pred)
round(auc(ROC_out), 4)

```