---
title: "Testing model covariates"
author: "Katy Gaythorpe"
date: "`r format(Sys.time(), '%d %B, %Y')`"
header-includes: 
- \usepackage{placeins}
output: 
  pdf_document:
    df_print: "kable"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

library(KsetupR)

library(dplyr)
library(magrittr)
library(corrplot)
library(ggplot2)
library(tidyr)
library(caret)

source('Functions/data_launch.R')
source("Functions/temp_suit.R")
```

```{r load_data}

Env_Table_path <- "../Data/Environment/global_dat"

filename <- KsetupR::get_latest_file(path = Env_Table_path, 
                                    pattern = "dat_wes")

dat <- read.csv(filename, stringsAsFactors = FALSE)

dat %<>% dplyr::select(-year)
dat %<>% filter( is.finite(MIR.max))
dat %<>% filter(!is.na(temp_mean))
#dat %<>% tidyr::drop_na()
dat %<>% mutate(continent = ifelse(adm0 %in% c("CIV", "STP"),
                                   "Africa", continent))

# make extra elements and normalise
dat = adjust_env_dat(dat)

```

```{r fit models}

covar_to_test <- names(dat)[9:(ncol(dat))]

covar_to_test <- covar_to_test[grep("surv.qual", covar_to_test, invert = TRUE)]
covar_to_test <- covar_to_test[grep("LC_dom", covar_to_test, invert = TRUE)]
covar_to_test <- covar_to_test[grep("risk", covar_to_test, invert = TRUE)]
covar_to_test <- covar_to_test[grep("population", covar_to_test, invert = TRUE)]
covar_to_test <- covar_to_test[grep("aggregate", covar_to_test, invert = TRUE)]
covar_to_test <- covar_to_test[grep("adm05", covar_to_test, invert = TRUE)]


# ------------------------------------------
# remove very correlated
filteredDescr <-  dat[, covar_to_test]
descrCor <-  cor(filteredDescr)


highlyCorDescr <- findCorrelation(descrCor, cutoff = .7)


filteredDescr <- filteredDescr[,-highlyCorDescr]

covar_to_test = names(filteredDescr)
# ------------------------------------------

mod <- list()
pvalues <- LLs <-  rep(NA, length(covar_to_test))
for(i in 1:length(covar_to_test)){
  mod[[i]] <- glm( paste0("cases_or_outbreaks~",covar_to_test[i]), 
           data = dat, family=binomial(link="cloglog"))
  
  pvalues[i] <- coef(summary(mod[[i]]))[,4]
  
  LLs[i] <- logLik(mod[[i]])
}

names(pvalues) <- covar_to_test

ind_to_keep <- which(pvalues < 0.05)

covar_to_test <- covar_to_test[ind_to_keep]

df <- data.frame(namesp = names(pvalues),
                pvalues = pvalues,
                LLs = LLs)

ggplot(df) + 
  geom_col( aes(x = namesp, y = pvalues)) + 
  theme_bw() + 
  theme(axis.text.x = element_text(angle = 90)) +
  xlab("Covariate")+
  ylab("P value of univariate model fit")+
  scale_y_log10()

df %>% arrange(-LLs)
```



Look at correlations.

```{r corr, fig.height=12}

cor_out <- cor(dat[, covar_to_test])

col2 <- colorRampPalette(c("#67001F", "#B2182B", "#D6604D", "#F4A582",
                           "#FDDBC7", "#FFFFFF", "#D1E5F0", "#92C5DE",
                           "#4393C3", "#2166AC", "#053061"))

corrplot::corrplot(cor_out, col =  col2(7), diag = FALSE, type = "upper")

```

```{r corr2}

tab_cor <- cor(dat$cases_or_outbreaks, dat[, covar_to_test])
corrplot::corrplot(tab_cor)

df <- data.frame(param = colnames(tab_cor),
                correlation = t(tab_cor))
df %>% arrange(-abs(correlation))

covar_to_test <- as.character( df$param[abs(df$correlation)>0.1])

df %<>% filter(param %in% covar_to_test)
```




## Clusters

```{r, fig.height=12, fig.width=10}

x <- as.dist( 1-abs(cor(na.omit(dat[, na.omit(covar_to_test)]))))

out <- hclust(x)

plot(out)

parm <- list()

ind <- 1
for(i in 2:length(na.omit(covar_to_test))){
  y <- cutree(out, k = i)
  
  df$cluster <- as.numeric(y[match(names(y), as.character(df$param) )])
  
  df %<>% arrange(-abs(correlation))
  
  parm[[ind]] <- df %>% 
    arrange(-abs(correlation)) %>% 
    group_by(cluster) %>% 
    summarise(parms = first(param)) #this picks the most correlated parameter out of each cluster
  
  ind <- ind+1
}



```

# Check fits


```{r fits}
mod <- list()
AICs <- rep(NA, length(parm))
LLs <- rep(NA, length(parm))
for(i in 1:length(parm)){
  
  model_form <- paste0("cases_or_outbreaks~", paste(parm[[i]]$parms, collapse = "+") )
  
  mod[[i]] <- glm( model_form, data = dat, family=binomial(link="cloglog"))
  AICs[i] <- AIC(mod[[i]])
  
  LLs[i] <- logLik(mod[[i]])
  
}

par(mfrow = c(1,2))
plot(LLs)
plot(AICs)

parm[[which.min(AICs)]]



```

```{r table_inclusion}

df_freq = as.data.frame(table(bind_rows(parm)$parms))

#discard those that are never chosen
df_freq %<>% filter(Freq>0)

df_freq %>% arrange(-Freq)

model_form <- paste0("cases_or_outbreaks~", paste(df_freq$Var1, collapse = "+") )

mod_freq = glm( model_form, data = dat, family=binomial(link="cloglog"))
```




```{r remove insiginficant}

final_mod <- mod_freq#mod[[which.min(AICs)]]

summary(final_mod)

pvalues <- coef(summary(final_mod))[,4]

parm_out <- names(pvalues)[pvalues < 0.05]
parm_out <- parm_out[-1]

model_form <- paste0("cases_or_outbreaks~", paste(parm_out, collapse = "+") )
  
mod <- glm( model_form, data = dat, family=binomial(link="cloglog"))



# write.csv(data.frame(x = model_form),
#                  "Model_form_e.csv",
#                  row.names = FALSE)

parm_out
```


# Land cover types

```{r, echo=FALSE}

data.frame( Name = c("Evergreen Needleleaf Forests",
                     "Evergreen Broadleaf Forests",
                     "Deciduous Needleleaf Forests",
                     "Deciduous Broadleaf Forests",
                     "Mixed Forests",
                     "Closed Shrublands",
                     "Open Shrublands",
                     "Woody Savannas",
                     "Savannas",
                     "Grasslands",
                     "Permanent Wetlands",
                     "Croplands",
                     "Urban and Built-up Lands",
                     "Cropland/Natural Vegetation Mosaics",
                     "Permanent Snow and Ice",
                     "Barren",
                     "Water Bodies"),
Landcover = c(1:16, 17) )

```

# Step wise?

```{r stepAIC, eval = FALSE}
covar_to_test <- names(dat)[9:(ncol(dat))]

covar_to_test <- covar_to_test[grep("surv.qual", covar_to_test, invert = TRUE)]
covar_to_test <- covar_to_test[grep("LC_dom", covar_to_test, invert = TRUE)]
covar_to_test <- covar_to_test[grep("risk", covar_to_test, invert = TRUE)]
covar_to_test <- covar_to_test[grep("population", covar_to_test, invert = TRUE)]
covar_to_test <- covar_to_test[grep("aggregate", covar_to_test, invert = TRUE)]
covar_to_test <- covar_to_test[grep("adm05", covar_to_test, invert = TRUE)]


# ------------------------------------------
# remove very correlated
filteredDescr <-  dat[, covar_to_test]
descrCor <-  cor(filteredDescr)


highlyCorDescr <- findCorrelation(descrCor, cutoff = .7)


filteredDescr <- filteredDescr[,-highlyCorDescr]

covar_to_test = names(filteredDescr)
#-------------------------------------------------

dat_subs = dat[, c("cases_or_outbreaks" ,covar_to_test)]

library(MASS)
alt_mod = MASS::stepAIC(glm("cases_or_outbreaks~.", data = dat_subs, 
                            family=binomial(link="cloglog")), trace = FALSE)
alt_mod$formula


pvalues <- coef(summary(alt_mod))[,4]

parm_out <- names(pvalues)[pvalues < 0.05]
parm_out <- parm_out[-1]

model_form <- paste0("cases_or_outbreaks~", paste(parm_out, collapse = "+") )
  
mod <- glm( model_form, data = dat, family=binomial(link="cloglog"))

parm_out

# write.csv(data.frame(x = model_form),
#                  "Model_form_step_1.csv",
#                  row.names = FALSE)

```